### PR TITLE
Fixing issue #23: Finder feature

### LINKED ISSUE #23: Finder Tab
For some users they have a lot of axies and trying to find specific ones to breed together can be annoying.

lets add another table with a finder tab
image

When it opens we get something similar like the offical marketplace https://marketplace.axieinfinity.com/axie
but we want to be searching of our Axies from all our accounts

image

We will need to to extend the Axie interface so that it gets all the information from AccountAxies.getAxies. Then we can create a map of all types of axies we have and the body parts we have, so that we can only can search for these types.

### PR DESCRIPTION
**Pull request by nnkhuongduy**
Fixes #23 

I have added a basic finder tab on dashboard. Can you help me with the Graphql query to find the axie detail from ronin address? (axie's image, id, ...)

### CODE REVIEW

**Comment by Jsuppers** [comment]
sure thing just added the parts with this commit https://github.com/Jsuppers/axie-pad/pull/29/commits/70f5b75562988864a2518f03f220e6d774a5a03a, we will just need to add all parts into a map in the finder component so we can pick a part from this map. If that makes sense :)

**Comment by nnkhuongduy** [comment]
@Jsuppers I have update the finder tab to display the axies. Can you help me check to see if I'm doing it correctly? Just to make sure we are having the same idea with this feature

**Comment by Jsuppers** [comment]
> @Jsuppers I have update the finder tab to display the axies. Can you help me check to see if I'm doing it correctly? Just to make sure we are having the same idea with this feature

This is turning out great thanks! Yes you are going in the right direction.

**Comment by nnkhuongduy** [comment]
@Jsuppers I think the feature is ready to be merged now. Please check and review and let me know if there's anything you want to change!

**Comment by Jsuppers** [comment]
@nnkhuongduy  this is looking great! can we also:
1. add sorting by class (it can be the same type of input as the parts)
2. add sorting by pureness this is a value between 0 and 6 (or any), so it can be a drop-down list. This is an exact match so if we select 2 only show axies with exactly 2 pureness
3. add sorting by breed count this can be a value between 0 and 7. We can also do this in a drop-down list but have the text say "Max breed count" and also have options 0-7 or any. This is a match with less then or equal to, so if you select 2 it shows all axies with a breed count less than or equal to 2
4. add sorting by quality (maybe a slide bar), this is a percentage between 0-100%. We should match axies that are equal or greater than the quality e.g. we enter 95, and it will match any axies with quality 95 or higher

I have updated the code to add the quality and pureness to the axie, so don't forget to run "npm install" :)

**Comment by Jsuppers** [comment]
looks great!

**Pull request merged**
