### PR TITLE
Fixing issue #8: Show badge error when request failed to retreive data

### LINKED ISSUE #8: show error when request failed to retreive data
When a scholar request failed we should show a warning on the group and on the actual scholar e.g.

image

we can use a badge for the group https://material.angular.io/components/badge/overview
and on the scholar we have a simple red mat-icon exclamation

### PR DESCRIPTION
**Pull request by nnkhuongduy**
Fixes #8 

I have added the warning badge to the SLP table to indicate which scholar has failed to retreive its data. Should I do the same for other 2 tables? If so how should we approach it? Even though the SLP data is failed the arena data and axies data are still fetched correctly

### CODE REVIEW

**Comment by Jsuppers** [comment]
> Fixes #8
> 
> I have added the warning badge to the SLP table to indicate which scholar has failed to retreive its data. Should I do the same for other 2 tables? If so how should we approach it? Even though the SLP data is failed the arena data and axies data are still fetched correctly

Yes please include it on the other tables. It visually looks good. I think we should instead have a property e.g. hasError, then when we retreive the data and there is a error we set this. e.g. 
image
and we can do the same for the slp and arena stats. Then on the frontend we can just check this property

**Comment by Jsuppers** [comment]
Could you also add a tooltip to the badge e.g. "There was a error retreiving data please refresh or check ronin address"

**Comment by Jsuppers** [comment]
I have also added a notifications feature, so we can see if a scholar has below a certain SLP (in the earnings table), and if axie count is below a certain amount (in axies tables). I think you could just add your condition as well e.g. in the earnings table we have now `[matBadgeHidden]="element.failedRules.length === 0"` this could change to `[matBadgeHidden]="element.failedRules.length === 0 || element.hasError"`

**Comment by Jsuppers** [comment]
could we also add a badge on the table tabs e.g. 
image
thanks!

**Comment by nnkhuongduy** [comment]
I have updated the error checking logic and added tooltip for error badges as well as the badge to table that has error on the main dashboard.

Can you help me check it out, I haven't added many axies to my own account so I might missed bugs here and there so let me know

**Comment by Jsuppers** [comment]
works well, just one thing is once I refresh the data for each error point it stills shows the table error: 
image

**Comment by Jsuppers** [comment]
Maybe, instead of returning the Axie[] list, we should create another interface:

```
interface AxieResult {
 hasError: boolean;
 axies: Axie[]
}
```
this way we can check only these results if has a error. then we can replace `this.tableError = this.tableError || (axies.length === 0 || leaderboardDetails.hasError);` with `this.tableError = this.tableError || axieResult.hasError`

**Comment by nnkhuongduy** [comment]
I have added a new AxieResult interface like you have mentioned and updated the error checking logic as well

**Comment by Jsuppers** [comment]
great thanks!

**Pull request merged**
