### PR TITLE
Fixing issue #9: Reformating the chart

### PR DESCRIPTION
**Pull request by nnkhuongduy**
I have skip some of the labels on Y axis, increased the chart height and reformat the date to have shorter weekday text.

Regarding of the data value, where should I get the In progress's Total/ Manager's share/ Scholar's share as well as the Projected value?

### CODE REVIEW

**Comment by Jsuppers** [comment]
this looks a lot better. I am thinking actually to remove the inprogress/projected values completely. Instead lets have it so we show the value we are going to get for each day e.g. something like this (where we use the same colors as the chart data, which projected on the top , then manager share, then scholar share)
image

**Comment by Jsuppers** [comment]
also maybe you want to combine this issue with it https://github.com/Jsuppers/axie-pad/issues/10, since we split the projected into projected manager share and projected scholar share. Thanks!

**Comment by nnkhuongduy** [comment]
Fixes #9 #10 

I have combined this issue with issue #10. The X axis's label has been updated but it seems like we cannot change the color for each label like the example image. How do you want to continue with this issue? Should we go back to in progess/ projected value table?
image

**Comment by Jsuppers** [comment]
> Fixes #9 #10
> 
> I have combined this issue with issue #10. The X axis's label has been updated but it seems like we cannot change the color for each label like the example image. How do you want to continue with this issue? Should we go back to in progess/ projected value table?
> image

This looks good, just leave it like this, maybe just round it to whole numbers. I will have a look in the weekend about the coloring :)

**Comment by Jsuppers** [comment]
just went with showing the managers share, thanks for this pr, graph looks a lot better now :)

**Pull request merged**
